build:
	@javac -d target src/question1/*.java src/question2/*.java

NodeApp:
	@java -cp target question1/NodeApp

LinkedListApp:
	@java -cp target question1/LinkedListApp

Recursion:
	@java -cp target question2/Recursion

zip:
	zip -r x23285508_SeanWelch.zip ./*